fix: (Sanity) Update SanityTest workflow
- improve artifact handling and job execution conditionality

	modified:   .github/workflows/sanityTest.yml

diff --git a/.github/workflows/sanityTest.yml b/.github/workflows/sanityTest.yml
--- a/.github/workflows/sanityTest.yml
+++ b/.github/workflows/sanityTest.yml
@@ -57,6 +57,8 @@ jobs:
     outputs:
       DEFAULT_XRAYKEY: ${{ env.DEFAULT_XRAY_KEY }}
       REPORT_DIR: ${{ env.MOCHA_REPORT_DIR }}
+      no_tests: ${{ steps.check-tests.outputs.no_tests }}
+      xray_tx: ${{ steps.assign-xray-data.outputs.testexec_key }}
     environment:
       name: ${{ github.event.inputs.environment }}
     env:
@@ -85,18 +87,70 @@ jobs:
       with:
         bun-version: latest
 
-    - name: 🧬 Install Project Dependencies
-      run: bun install
-
     - name: 🔎 Check Typescript Code
       run: | #? Corre el linter de TypeScript para verificar errores de sintaxis.
         bun run check:ts
 
-    - name: Check Cypress Installation
+    - name: Check for Tests
+      id: check-tests
       run: |
-        which cypress || bun install cypress
+        test_run="${{ github.event.inputs.test_run }}"
 
-    - name: 📦 Prepare Artifact
+        # Elimina los espacios al principio y al final
+        test_run=$(echo "$test_run" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
+
+        if [[ ! -f "$test_run" || ! "$test_run" =~ \.cy\.[jt]s$ ]]; then
+          echo "No test found"
+          echo "no_tests=true" >> $GITHUB_OUTPUT
+        else
+          if grep -q "expect" "$test_run" || grep -q "it(" "$test_run"; then
+            echo "Tests found"
+            echo "no_tests=false" >> $GITHUB_OUTPUT
+          else
+            echo "No test found"
+            echo "no_tests=true" >> $GITHUB_OUTPUT
+          fi
+        fi
+
+    - name: Extract Xray TX from Selected File
+      id: extract-xray-data
+      run: |
+        if [[ "$(basename "${{ github.event.inputs.test_run }}")" =~ ^(GX[1-4])-([0-9]+)(_|-)(.+)\.(cy\.ts|cy\.js)$ ]]; then
+          xray_tx="${BASH_REMATCH[1]}-${BASH_REMATCH[2]}"
+          echo "Extracted Xray TX: $xray_tx"
+        else 
+          echo "No valid Xray TX found in the file name."
+        fi
+
+    - name: Assign Xray TX
+      id: assign-xray-data
+      run: |
+        testexec_key="${{ env.DEFAULT_XRAY_KEY }}"
+        #needs.Server_Config.outputs.DEFAULT_XRAYKEY
+
+        if [ -n "${{ github.event.inputs.xray_tx }}" ]; then
+          testexec_key="${{ github.event.inputs.xray_tx }}"
+        elif [ -n "$xray_tx" ]; then
+          testexec_key="$xray_tx"
+        fi
+
+        echo "Using testexec_key: $testexec_key"
+        echo "testexec_key=$testexec_key" >> $GITHUB_OUTPUT
+
+    - name: 🧬 Install Project Dependencies
+      run: bun install
+
+    #- name: Check Cypress Installation
+    #  run: |
+    #    which cypress || bun install cypres
+
+    - name: 📂 Ensure Test Result Directories Exist
+      run: |
+        # Crear las carpetas necesarias solo si no existen
+        mkdir -p cypress/tests_results/junit/chrome
+        mkdir -p cypress/tests_results/mocha/chrome
+
+    - name: 📦 Prepare Temporary Folder for Artifacts
       run: |
         mkdir -p temp_artifact
         cp -R cypress temp_artifact/
@@ -111,37 +165,12 @@ jobs:
         name: cypress-structure
         path: temp_artifact/
         overwrite: true
-
-  Xray_Data_Extraction:
-    needs: Server_Config
-    runs-on: ${{ github.event.inputs.system }}
-    outputs:
-      xray_tx: ${{ steps.assign-xray-data.outputs.testexec_key }}
-    steps:
-    - name: Extract Xray TX from Selected File
-      id: extract-xray-data
-      run: |
-        if [[ "$(basename "${{ github.event.inputs.test_run }}")" =~ ^(GX[1-4])-([0-9]+)(_|-)(.+)\.(cy\.ts|cy\.js)$ ]]; then
-          xray_tx="${BASH_REMATCH[1]}-${BASH_REMATCH[2]}"
-          echo "Extracted Xray TX: $xray_tx"
-        fi
-
-    - name: Assign Xray TX
-      id: assign-xray-data
-      run: |
-        testexec_key="${{ needs.Server_Config.outputs.DEFAULT_XRAYKEY }}"
-        if [ -n "${{ github.event.inputs.xray_tx }}" ]; then
-          testexec_key="${{ github.event.inputs.xray_tx }}"
-        elif [ -n "$xray_tx" ]; then
-          testexec_key="$xray_tx"
-        fi
-        echo "testexec_key=$testexec_key" >> $GITHUB_OUTPUT
+        retention-days: 15
 
   SanityTest:
     needs: Server_Config
     runs-on: ${{ github.event.inputs.system }}
     outputs:
-      no_tests: ${{ steps.check-tests.outputs.no_tests }}
       result: ${{ job.status }}
     steps:
     - name: 🍙 Bun Setup
@@ -162,43 +191,54 @@ jobs:
 
     - name: Check Cypress Installation
       run: |
-        which cypress || bun install cypress
-
-    - name: Check for Tests
-      id: check-tests
-      run: |
-        test_run="${{ github.event.inputs.test_run }}"
-        # Elimina los espacios al principio y al final
-        test_run=$(echo "$test_run" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
-    
-        if [ ! -f "$test_run" ]; then
-          echo "no_tests=true" >> $GITHUB_OUTPUT
+        if ! which cypress > /dev/null; then
+          echo "Cypress not found. Installing ..."
+          bun install cypress
         else
-          if grep -q "expect" "$test_run" || grep -q "it(" "$test_run"; then
-            echo "no_tests=false" >> $GITHUB_OUTPUT
-          else
-            echo "no_tests=true" >> $GITHUB_OUTPUT
-          fi
+          echo "Cypress is already installed."
         fi
 
     - name: 🧪 Cypress Run Sanity Test
       id: cypress-run
-      if: steps.check-tests.outputs.no_tests == 'false'
-      run: bun x cypress run --browser ${{ github.event.inputs.browser }} --spec ${{ github.event.inputs.test_run }} --headless
+      if: needs.Server_Config.outputs.no_tests == 'false'
+      run: bun x cypress run --browser ${{ github.event.inputs.browser }} --spec ${{ github.event.inputs.test_run }}
+
+    - name: 📦 Prepare Temporary Folder for Results and Config
+      run: |
+        mkdir -p temp_artifact
+        cp -R cypress/tests_results/ temp_artifact/
+        cp tsconfig.* temp_artifact/
+        cp cypress.* temp_artifact/
+        cp package.json temp_artifact/
+        cp bun.lockb temp_artifact/
+
+    - name: 📦 Upload Cypress Results and Config
+      if: needs.Server_Config.outputs.no_tests == 'false'
+      uses: actions/upload-artifact@v4
+      with:
+        name: cypress-results-and-config
+        path: temp_artifact/
+        retention-days: 15
 
   Reports_Generation:
-    needs: [ SanityTest, Server_Config, Xray_Data_Extraction ]
+    needs: [ SanityTest, Server_Config ]
     runs-on: ${{ github.event.inputs.system }}
+    if: needs.Server_Config.outputs.no_tests == 'false'
     steps:
     - name: 🍙 Bun Setup
       uses: oven-sh/setup-bun@v2
       with:
         bun-version: latest
 
-    - name: 📥 Download Cypress Structure
+    - name: 📥 Download Cypress Results and Config
       uses: actions/download-artifact@v4
       with:
-        name: cypress-structure
+        name: cypress-results-and-config
+
+    #- name: 📥 Download Cypress Structure
+    #  uses: actions/download-artifact@v4
+    #  with:
+    #    name: cypress-structure
 
     - name: 🗄️ Restore Node Modules Cache
       uses: actions/cache@v3
@@ -206,19 +246,13 @@ jobs:
         path: ~/.bun
         key: ${{ github.event.inputs.system }}-bun-${{ hashFiles('**/bun.lockb') }}
 
-    - name: 📂 Ensure Test Result Directories Exist
-      run: |
-        mkdir -p cypress/tests_results/junit/chrome
-        mkdir -p cypress/tests_results/mocha/chrome
-        mkdir -p cypress/tests_results
-
     - name: 📬 Check for JRM and Install if Missing
       run: |
         if ! command -v jrm &>/dev/null; then
-          echo "jrm not found, installing..."
+          echo "JRM not found, installing..."
           bun add -d junit-report-merger
         else
-          echo "jrm is already installed."
+          echo "JRM is already installed."
         fi
 
     - name: 📥 Run Chrome Report
@@ -236,11 +270,11 @@ jobs:
         fi
 
     - name: 📬 Generate JUnit/Mocha Report
-      if: always() && needs.SanityTest.outputs.no_tests == 'false'
+      if: always()
       run: bun run chrome:report
 
     - name: 📊 Upload Artifact Mochawesome Report
-      if: always() && needs.SanityTest.outputs.no_tests == 'false'
+      if: always()
       uses: actions/upload-artifact@v4
       with:
         name: sanity-mocha-report
@@ -248,21 +282,17 @@ jobs:
         retention-days: 15
 
     - name: 🚀 Deploy Mocha Report to GitHub Pages
-      if: always() && needs.SanityTest.outputs.no_tests == 'false'
+      if: always()
       uses: peaceiris/actions-gh-pages@v4
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_branch: gh-pages #? the branch used for the GitHub Pages content.
-        destination_dir: sanity/${{ needs.Xray_Data_Extraction.outputs.xray_tx }} #? this is the directory inside the gh-pages branch where the MOCHA_REPORT_DIR will be saved.
+        destination_dir: sanity/${{ needs.Server_Config.outputs.xray_tx }} #? this is the directory inside the gh-pages branch where the MOCHA_REPORT_DIR will be saved.
         publish_dir: ${{ needs.Server_Config.outputs.REPORT_DIR }} #? the directory to be published.
         keep_files: true #? true is required to work properly with the subfolder option in the Build Allure Report step.
 
-    - name: Debug Check Tests Output
-      run: |
-        echo "Check Tests Output: ${{ needs.SanityTest.outputs.no_tests }}"
-
   Notification:
-    needs: [ Reports_Generation, SanityTest ]
+    needs: [ SanityTest, Server_Config ]
     if: always()
     runs-on: ubuntu-latest
     steps:
@@ -270,14 +300,16 @@ jobs:
     - name: Prepare Message
       id: prepare-message
       run: |
-        SLACK_MESSAGE="🧪(${GITHUB_REPOSITORY}): ${GITHUB_ACTOR} triggered SanityTest 🚀 \nResult: *$(echo '${{ needs.SanityTest.outputs.result }}' | tr '[:lower:]' '[:upper:]')*"
+        SLACK_MESSAGE="🧪(${GITHUB_REPOSITORY}): ${GITHUB_ACTOR} triggered SanityTest 🚀"
+
+        if [ "${{ needs.Server_Config.outputs.no_tests }}" == "true" ]; then
+          SLACK_MESSAGE="$SLACK_MESSAGE \nResult: *NO TEST FOUND*"
+        else
+          SLACK_MESSAGE="$SLACK_MESSAGE \nResult: *$(echo '${{ needs.SanityTest.outputs.result }}' | tr '[:lower:]' '[:upper:]')*"
+        fi
+
         echo "SLACK_MESSAGE=$SLACK_MESSAGE" >> $GITHUB_ENV
 
-    - name: Create Manual Slack Message
+    - name: Display Slack Message
       run: |
-        echo "🧪(${{ github.repository }}): ${{ github.actor }} triggered SanityTest🚀"
-        if [ "${{ needs.SanityTest.outputs.no_tests }}" == "true" ]; then
-          echo "Result: *NO TEST FOUND*"
-        else
-          echo "Result: *$(echo "${{ needs.SanityTest.outputs.result }}" | tr '[:lower:]' '[:upper:]')*"
-        fi
+        echo "SLACK MESSAGE: ${{ steps.prepare-message.outputs.slack_message }}"
